sonar.projectKey=sonar-demo-vulneravel
sonar.projectName=Sonar Demo Vulnerável
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Diretório com o código fonte
sonar.sources=src

# URL do servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticação (vai mudar na hora, você gera no SonarQube)
sonar.login=sqp_4462481b613dd03960fc134ab972d5d5f7195f68

sonar.javascript.lcov.reportPaths=coverage/lcov.info
