package br.edu.idp.es.stsw.bva.unit;

import static br.edu.idp.es.stsw.bva.unit.DroneMissionTestSpecification.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import br.edu.idp.es.stsw.bva.domain.DroneMissionPolicy;

class RobustWorstCaseBvaTest {

    private final DroneMissionPolicy policy = new DroneMissionPolicy();

    @ParameterizedTest(name = "[{index}] missão com bateria={0}, vento={1}, pesoCarga={2} deve ser {3}")
    @CsvSource({
            (MIN_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MIN_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (NOMINAL_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY - 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + AUTHORIZED,
            (MAX_BATTERY) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MIN_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (NOMINAL_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND - 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MIN_PAYLOAD_WEIGHT + 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (NOMINAL_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT - 1) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT) + ", " + DENIED,
            (MAX_BATTERY + 1) + ", " + (MAX_WIND + 1) + ", " + (MAX_PAYLOAD_WEIGHT + 1) + ", " + DENIED
    })
    @DisplayName("Decide a missão para todas as combinações de condições próximas e além dos limites operacionais")
    void shouldDecideMissionForEveryCombinationNearAndBeyondOperationalLimits(
            int battery,
            int wind,
            int payloadWeight,
            String expectedDecision) {
        assertEquals(expectedDecision, policy.evaluate(battery, wind, payloadWeight));
    }
}
