Feature: Autorizar missões de drones
  Como equipe da Defesa Civil
  Quero validar missões de drones
  Para reduzir o risco de autorizar operações inseguras

  Rule: A missão só é autorizada quando bateria, vento e peso da carga estão dentro dos limites

    @bva-normal
    Scenario Outline: Autorizar a missão ao avaliar individualmente cada condição nos limites operacionais
      When eu avalio uma missão com bateria <bateria>, vento <vento> e peso da carga <pesoCarga>
      Then a missão deve ser "<resultado>"

      Examples:
        | bateria | vento | pesoCarga | resultado  |
        | 70      | 20    | 4         | AUTORIZADA |
        | 30      | 20    | 4         | AUTORIZADA |
        | 31      | 20    | 4         | AUTORIZADA |
        | 99      | 20    | 4         | AUTORIZADA |
        | 100     | 20    | 4         | AUTORIZADA |
        | 70      | 0     | 4         | AUTORIZADA |
        | 70      | 1     | 4         | AUTORIZADA |
        | 70      | 39    | 4         | AUTORIZADA |
        | 70      | 40    | 4         | AUTORIZADA |
        | 70      | 20    | 1         | AUTORIZADA |
        | 70      | 20    | 2         | AUTORIZADA |
        | 70      | 20    | 7         | AUTORIZADA |
        | 70      | 20    | 8         | NEGADA     |

    @bva-robusto
    Scenario Outline: Decidir a missão ao avaliar individualmente condições dentro e fora dos limites operacionais
      When eu avalio uma missão com bateria <bateria>, vento <vento> e peso da carga <pesoCarga>
      Then a missão deve ser "<resultado>"

      Examples:
        | bateria | vento | pesoCarga | resultado  |
        | 70      | 20    | 4         | AUTORIZADA |
        | 29      | 20    | 4         | NEGADA     |
        | 30      | 20    | 4         | AUTORIZADA |
        | 31      | 20    | 4         | AUTORIZADA |
        | 99      | 20    | 4         | AUTORIZADA |
        | 100     | 20    | 4         | AUTORIZADA |
        | 101     | 20    | 4         | NEGADA     |
        | 70      | -1    | 4         | NEGADA     |
        | 70      | 0     | 4         | AUTORIZADA |
        | 70      | 1     | 4         | AUTORIZADA |
        | 70      | 39    | 4         | AUTORIZADA |
        | 70      | 40    | 4         | AUTORIZADA |
        | 70      | 41    | 4         | NEGADA     |
        | 70      | 20    | 0         | NEGADA     |
        | 70      | 20    | 1         | AUTORIZADA |
        | 70      | 20    | 2         | AUTORIZADA |
        | 70      | 20    | 7         | AUTORIZADA |
        | 70      | 20    | 8         | AUTORIZADA |
        | 70      | 20    | 9         | NEGADA     |

    @worst-case
    Scenario Outline: Autorizar a missão para todas as combinações de condições permitidas próximas aos limites
      When eu avalio uma missão com bateria <bateria>, vento <vento> e peso da carga <pesoCarga>
      Then a missão deve ser "<resultado>"

      Examples:
        | bateria | vento | pesoCarga | resultado  |
        | 30      | 0     | 1         | AUTORIZADA |
        | 30      | 0     | 2         | AUTORIZADA |
        | 30      | 0     | 4         | AUTORIZADA |
        | 30      | 0     | 7         | AUTORIZADA |
        | 30      | 0     | 8         | AUTORIZADA |
        | 30      | 1     | 1         | AUTORIZADA |
        | 30      | 1     | 2         | AUTORIZADA |
        | 30      | 1     | 4         | AUTORIZADA |
        | 30      | 1     | 7         | AUTORIZADA |
        | 30      | 1     | 8         | AUTORIZADA |
        | 30      | 20    | 1         | AUTORIZADA |
        | 30      | 20    | 2         | AUTORIZADA |
        | 30      | 20    | 4         | AUTORIZADA |
        | 30      | 20    | 7         | AUTORIZADA |
        | 30      | 20    | 8         | AUTORIZADA |
        | 30      | 39    | 1         | AUTORIZADA |
        | 30      | 39    | 2         | AUTORIZADA |
        | 30      | 39    | 4         | AUTORIZADA |
        | 30      | 39    | 7         | AUTORIZADA |
        | 30      | 39    | 8         | AUTORIZADA |
        | 30      | 40    | 1         | AUTORIZADA |
        | 30      | 40    | 2         | AUTORIZADA |
        | 30      | 40    | 4         | AUTORIZADA |
        | 30      | 40    | 7         | AUTORIZADA |
        | 30      | 40    | 8         | AUTORIZADA |
        | 31      | 0     | 1         | AUTORIZADA |
        | 31      | 0     | 2         | AUTORIZADA |
        | 31      | 0     | 4         | AUTORIZADA |
        | 31      | 0     | 7         | AUTORIZADA |
        | 31      | 0     | 8         | AUTORIZADA |
        | 31      | 1     | 1         | AUTORIZADA |
        | 31      | 1     | 2         | AUTORIZADA |
        | 31      | 1     | 4         | AUTORIZADA |
        | 31      | 1     | 7         | AUTORIZADA |
        | 31      | 1     | 8         | AUTORIZADA |
        | 31      | 20    | 1         | AUTORIZADA |
        | 31      | 20    | 2         | AUTORIZADA |
        | 31      | 20    | 4         | AUTORIZADA |
        | 31      | 20    | 7         | AUTORIZADA |
        | 31      | 20    | 8         | AUTORIZADA |
        | 31      | 39    | 1         | AUTORIZADA |
        | 31      | 39    | 2         | AUTORIZADA |
        | 31      | 39    | 4         | AUTORIZADA |
        | 31      | 39    | 7         | AUTORIZADA |
        | 31      | 39    | 8         | AUTORIZADA |
        | 31      | 40    | 1         | AUTORIZADA |
        | 31      | 40    | 2         | AUTORIZADA |
        | 31      | 40    | 4         | AUTORIZADA |
        | 31      | 40    | 7         | AUTORIZADA |
        | 31      | 40    | 8         | AUTORIZADA |
        | 70      | 0     | 1         | AUTORIZADA |
        | 70      | 0     | 2         | AUTORIZADA |
        | 70      | 0     | 4         | AUTORIZADA |
        | 70      | 0     | 7         | AUTORIZADA |
        | 70      | 0     | 8         | AUTORIZADA |
        | 70      | 1     | 1         | AUTORIZADA |
        | 70      | 1     | 2         | AUTORIZADA |
        | 70      | 1     | 4         | AUTORIZADA |
        | 70      | 1     | 7         | AUTORIZADA |
        | 70      | 1     | 8         | AUTORIZADA |
        | 70      | 20    | 1         | AUTORIZADA |
        | 70      | 20    | 2         | AUTORIZADA |
        | 70      | 20    | 4         | AUTORIZADA |
        | 70      | 20    | 7         | AUTORIZADA |
        | 70      | 20    | 8         | AUTORIZADA |
        | 70      | 39    | 1         | AUTORIZADA |
        | 70      | 39    | 2         | AUTORIZADA |
        | 70      | 39    | 4         | AUTORIZADA |
        | 70      | 39    | 7         | AUTORIZADA |
        | 70      | 39    | 8         | AUTORIZADA |
        | 70      | 40    | 1         | AUTORIZADA |
        | 70      | 40    | 2         | AUTORIZADA |
        | 70      | 40    | 4         | AUTORIZADA |
        | 70      | 40    | 7         | AUTORIZADA |
        | 70      | 40    | 8         | AUTORIZADA |
        | 99      | 0     | 1         | AUTORIZADA |
        | 99      | 0     | 2         | AUTORIZADA |
        | 99      | 0     | 4         | AUTORIZADA |
        | 99      | 0     | 7         | AUTORIZADA |
        | 99      | 0     | 8         | AUTORIZADA |
        | 99      | 1     | 1         | AUTORIZADA |
        | 99      | 1     | 2         | AUTORIZADA |
        | 99      | 1     | 4         | AUTORIZADA |
        | 99      | 1     | 7         | AUTORIZADA |
        | 99      | 1     | 8         | AUTORIZADA |
        | 99      | 20    | 1         | AUTORIZADA |
        | 99      | 20    | 2         | AUTORIZADA |
        | 99      | 20    | 4         | AUTORIZADA |
        | 99      | 20    | 7         | AUTORIZADA |
        | 99      | 20    | 8         | AUTORIZADA |
        | 99      | 39    | 1         | AUTORIZADA |
        | 99      | 39    | 2         | AUTORIZADA |
        | 99      | 39    | 4         | AUTORIZADA |
        | 99      | 39    | 7         | AUTORIZADA |
        | 99      | 39    | 8         | AUTORIZADA |
        | 99      | 40    | 1         | AUTORIZADA |
        | 99      | 40    | 2         | AUTORIZADA |
        | 99      | 40    | 4         | AUTORIZADA |
        | 99      | 40    | 7         | AUTORIZADA |
        | 99      | 40    | 8         | AUTORIZADA |
        | 100     | 0     | 1         | AUTORIZADA |
        | 100     | 0     | 2         | AUTORIZADA |
        | 100     | 0     | 4         | AUTORIZADA |
        | 100     | 0     | 7         | AUTORIZADA |
        | 100     | 0     | 8         | AUTORIZADA |
        | 100     | 1     | 1         | AUTORIZADA |
        | 100     | 1     | 2         | AUTORIZADA |
        | 100     | 1     | 4         | AUTORIZADA |
        | 100     | 1     | 7         | AUTORIZADA |
        | 100     | 1     | 8         | AUTORIZADA |
        | 100     | 20    | 1         | AUTORIZADA |
        | 100     | 20    | 2         | AUTORIZADA |
        | 100     | 20    | 4         | AUTORIZADA |
        | 100     | 20    | 7         | AUTORIZADA |
        | 100     | 20    | 8         | AUTORIZADA |
        | 100     | 39    | 1         | AUTORIZADA |
        | 100     | 39    | 2         | AUTORIZADA |
        | 100     | 39    | 4         | AUTORIZADA |
        | 100     | 39    | 7         | AUTORIZADA |
        | 100     | 39    | 8         | AUTORIZADA |
        | 100     | 40    | 1         | AUTORIZADA |
        | 100     | 40    | 2         | AUTORIZADA |
        | 100     | 40    | 4         | AUTORIZADA |
        | 100     | 40    | 7         | AUTORIZADA |
        | 100     | 40    | 8         | AUTORIZADA |

    @robust-worst-case
    Scenario Outline: Decidir a missão para todas as combinações de condições próximas e além dos limites operacionais
      When eu avalio uma missão com bateria <bateria>, vento <vento> e peso da carga <pesoCarga>
      Then a missão deve ser "<resultado>"

      Examples:
        | bateria | vento | pesoCarga | resultado  |
        | 29      | -1    | 0         | NEGADA     |
        | 29      | -1    | 1         | NEGADA     |
        | 29      | -1    | 2         | NEGADA     |
        | 29      | -1    | 4         | NEGADA     |
        | 29      | -1    | 7         | NEGADA     |
        | 29      | -1    | 8         | NEGADA     |
        | 29      | -1    | 9         | NEGADA     |
        | 29      | 0     | 0         | NEGADA     |
        | 29      | 0     | 1         | NEGADA     |
        | 29      | 0     | 2         | NEGADA     |
        | 29      | 0     | 4         | NEGADA     |
        | 29      | 0     | 7         | NEGADA     |
        | 29      | 0     | 8         | NEGADA     |
        | 29      | 0     | 9         | NEGADA     |
        | 29      | 1     | 0         | NEGADA     |
        | 29      | 1     | 1         | NEGADA     |
        | 29      | 1     | 2         | NEGADA     |
        | 29      | 1     | 4         | NEGADA     |
        | 29      | 1     | 7         | NEGADA     |
        | 29      | 1     | 8         | NEGADA     |
        | 29      | 1     | 9         | NEGADA     |
        | 29      | 20    | 0         | NEGADA     |
        | 29      | 20    | 1         | NEGADA     |
        | 29      | 20    | 2         | NEGADA     |
        | 29      | 20    | 4         | NEGADA     |
        | 29      | 20    | 7         | NEGADA     |
        | 29      | 20    | 8         | NEGADA     |
        | 29      | 20    | 9         | NEGADA     |
        | 29      | 39    | 0         | NEGADA     |
        | 29      | 39    | 1         | NEGADA     |
        | 29      | 39    | 2         | NEGADA     |
        | 29      | 39    | 4         | NEGADA     |
        | 29      | 39    | 7         | NEGADA     |
        | 29      | 39    | 8         | NEGADA     |
        | 29      | 39    | 9         | NEGADA     |
        | 29      | 40    | 0         | NEGADA     |
        | 29      | 40    | 1         | NEGADA     |
        | 29      | 40    | 2         | NEGADA     |
        | 29      | 40    | 4         | NEGADA     |
        | 29      | 40    | 7         | NEGADA     |
        | 29      | 40    | 8         | NEGADA     |
        | 29      | 40    | 9         | NEGADA     |
        | 29      | 41    | 0         | NEGADA     |
        | 29      | 41    | 1         | NEGADA     |
        | 29      | 41    | 2         | NEGADA     |
        | 29      | 41    | 4         | NEGADA     |
        | 29      | 41    | 7         | NEGADA     |
        | 29      | 41    | 8         | NEGADA     |
        | 29      | 41    | 9         | NEGADA     |
        | 30      | -1    | 0         | NEGADA     |
        | 30      | -1    | 1         | NEGADA     |
        | 30      | -1    | 2         | NEGADA     |
        | 30      | -1    | 4         | NEGADA     |
        | 30      | -1    | 7         | NEGADA     |
        | 30      | -1    | 8         | NEGADA     |
        | 30      | -1    | 9         | NEGADA     |
        | 30      | 0     | 0         | NEGADA     |
        | 30      | 0     | 1         | AUTORIZADA |
        | 30      | 0     | 2         | AUTORIZADA |
        | 30      | 0     | 4         | AUTORIZADA |
        | 30      | 0     | 7         | AUTORIZADA |
        | 30      | 0     | 8         | AUTORIZADA |
        | 30      | 0     | 9         | NEGADA     |
        | 30      | 1     | 0         | NEGADA     |
        | 30      | 1     | 1         | AUTORIZADA |
        | 30      | 1     | 2         | AUTORIZADA |
        | 30      | 1     | 4         | AUTORIZADA |
        | 30      | 1     | 7         | AUTORIZADA |
        | 30      | 1     | 8         | AUTORIZADA |
        | 30      | 1     | 9         | NEGADA     |
        | 30      | 20    | 0         | NEGADA     |
        | 30      | 20    | 1         | AUTORIZADA |
        | 30      | 20    | 2         | AUTORIZADA |
        | 30      | 20    | 4         | AUTORIZADA |
        | 30      | 20    | 7         | AUTORIZADA |
        | 30      | 20    | 8         | AUTORIZADA |
        | 30      | 20    | 9         | NEGADA     |
        | 30      | 39    | 0         | NEGADA     |
        | 30      | 39    | 1         | AUTORIZADA |
        | 30      | 39    | 2         | AUTORIZADA |
        | 30      | 39    | 4         | AUTORIZADA |
        | 30      | 39    | 7         | AUTORIZADA |
        | 30      | 39    | 8         | AUTORIZADA |
        | 30      | 39    | 9         | NEGADA     |
        | 30      | 40    | 0         | NEGADA     |
        | 30      | 40    | 1         | AUTORIZADA |
        | 30      | 40    | 2         | AUTORIZADA |
        | 30      | 40    | 4         | AUTORIZADA |
        | 30      | 40    | 7         | AUTORIZADA |
        | 30      | 40    | 8         | AUTORIZADA |
        | 30      | 40    | 9         | NEGADA     |
        | 30      | 41    | 0         | NEGADA     |
        | 30      | 41    | 1         | NEGADA     |
        | 30      | 41    | 2         | NEGADA     |
        | 30      | 41    | 4         | NEGADA     |
        | 30      | 41    | 7         | NEGADA     |
        | 30      | 41    | 8         | NEGADA     |
        | 30      | 41    | 9         | NEGADA     |
        | 31      | -1    | 0         | NEGADA     |
        | 31      | -1    | 1         | NEGADA     |
        | 31      | -1    | 2         | NEGADA     |
        | 31      | -1    | 4         | NEGADA     |
        | 31      | -1    | 7         | NEGADA     |
        | 31      | -1    | 8         | NEGADA     |
        | 31      | -1    | 9         | NEGADA     |
        | 31      | 0     | 0         | NEGADA     |
        | 31      | 0     | 1         | AUTORIZADA |
        | 31      | 0     | 2         | AUTORIZADA |
        | 31      | 0     | 4         | AUTORIZADA |
        | 31      | 0     | 7         | AUTORIZADA |
        | 31      | 0     | 8         | AUTORIZADA |
        | 31      | 0     | 9         | NEGADA     |
        | 31      | 1     | 0         | NEGADA     |
        | 31      | 1     | 1         | AUTORIZADA |
        | 31      | 1     | 2         | AUTORIZADA |
        | 31      | 1     | 4         | AUTORIZADA |
        | 31      | 1     | 7         | AUTORIZADA |
        | 31      | 1     | 8         | AUTORIZADA |
        | 31      | 1     | 9         | NEGADA     |
        | 31      | 20    | 0         | NEGADA     |
        | 31      | 20    | 1         | AUTORIZADA |
        | 31      | 20    | 2         | AUTORIZADA |
        | 31      | 20    | 4         | AUTORIZADA |
        | 31      | 20    | 7         | AUTORIZADA |
        | 31      | 20    | 8         | AUTORIZADA |
        | 31      | 20    | 9         | NEGADA     |
        | 31      | 39    | 0         | NEGADA     |
        | 31      | 39    | 1         | AUTORIZADA |
        | 31      | 39    | 2         | AUTORIZADA |
        | 31      | 39    | 4         | AUTORIZADA |
        | 31      | 39    | 7         | AUTORIZADA |
        | 31      | 39    | 8         | AUTORIZADA |
        | 31      | 39    | 9         | NEGADA     |
        | 31      | 40    | 0         | NEGADA     |
        | 31      | 40    | 1         | AUTORIZADA |
        | 31      | 40    | 2         | AUTORIZADA |
        | 31      | 40    | 4         | AUTORIZADA |
        | 31      | 40    | 7         | AUTORIZADA |
        | 31      | 40    | 8         | AUTORIZADA |
        | 31      | 40    | 9         | NEGADA     |
        | 31      | 41    | 0         | NEGADA     |
        | 31      | 41    | 1         | NEGADA     |
        | 31      | 41    | 2         | NEGADA     |
        | 31      | 41    | 4         | NEGADA     |
        | 31      | 41    | 7         | NEGADA     |
        | 31      | 41    | 8         | NEGADA     |
        | 31      | 41    | 9         | NEGADA     |
        | 70      | -1    | 0         | NEGADA     |
        | 70      | -1    | 1         | NEGADA     |
        | 70      | -1    | 2         | NEGADA     |
        | 70      | -1    | 4         | NEGADA     |
        | 70      | -1    | 7         | NEGADA     |
        | 70      | -1    | 8         | NEGADA     |
        | 70      | -1    | 9         | NEGADA     |
        | 70      | 0     | 0         | NEGADA     |
        | 70      | 0     | 1         | AUTORIZADA |
        | 70      | 0     | 2         | AUTORIZADA |
        | 70      | 0     | 4         | AUTORIZADA |
        | 70      | 0     | 7         | AUTORIZADA |
        | 70      | 0     | 8         | AUTORIZADA |
        | 70      | 0     | 9         | NEGADA     |
        | 70      | 1     | 0         | NEGADA     |
        | 70      | 1     | 1         | AUTORIZADA |
        | 70      | 1     | 2         | AUTORIZADA |
        | 70      | 1     | 4         | AUTORIZADA |
        | 70      | 1     | 7         | AUTORIZADA |
        | 70      | 1     | 8         | AUTORIZADA |
        | 70      | 1     | 9         | NEGADA     |
        | 70      | 20    | 0         | NEGADA     |
        | 70      | 20    | 1         | AUTORIZADA |
        | 70      | 20    | 2         | AUTORIZADA |
        | 70      | 20    | 4         | AUTORIZADA |
        | 70      | 20    | 7         | AUTORIZADA |
        | 70      | 20    | 8         | AUTORIZADA |
        | 70      | 20    | 9         | NEGADA     |
        | 70      | 39    | 0         | NEGADA     |
        | 70      | 39    | 1         | AUTORIZADA |
        | 70      | 39    | 2         | AUTORIZADA |
        | 70      | 39    | 4         | AUTORIZADA |
        | 70      | 39    | 7         | AUTORIZADA |
        | 70      | 39    | 8         | AUTORIZADA |
        | 70      | 39    | 9         | NEGADA     |
        | 70      | 40    | 0         | NEGADA     |
        | 70      | 40    | 1         | AUTORIZADA |
        | 70      | 40    | 2         | AUTORIZADA |
        | 70      | 40    | 4         | AUTORIZADA |
        | 70      | 40    | 7         | AUTORIZADA |
        | 70      | 40    | 8         | AUTORIZADA |
        | 70      | 40    | 9         | NEGADA     |
        | 70      | 41    | 0         | NEGADA     |
        | 70      | 41    | 1         | NEGADA     |
        | 70      | 41    | 2         | NEGADA     |
        | 70      | 41    | 4         | NEGADA     |
        | 70      | 41    | 7         | NEGADA     |
        | 70      | 41    | 8         | NEGADA     |
        | 70      | 41    | 9         | NEGADA     |
        | 99      | -1    | 0         | NEGADA     |
        | 99      | -1    | 1         | NEGADA     |
        | 99      | -1    | 2         | NEGADA     |
        | 99      | -1    | 4         | NEGADA     |
        | 99      | -1    | 7         | NEGADA     |
        | 99      | -1    | 8         | NEGADA     |
        | 99      | -1    | 9         | NEGADA     |
        | 99      | 0     | 0         | NEGADA     |
        | 99      | 0     | 1         | AUTORIZADA |
        | 99      | 0     | 2         | AUTORIZADA |
        | 99      | 0     | 4         | AUTORIZADA |
        | 99      | 0     | 7         | AUTORIZADA |
        | 99      | 0     | 8         | AUTORIZADA |
        | 99      | 0     | 9         | NEGADA     |
        | 99      | 1     | 0         | NEGADA     |
        | 99      | 1     | 1         | AUTORIZADA |
        | 99      | 1     | 2         | AUTORIZADA |
        | 99      | 1     | 4         | AUTORIZADA |
        | 99      | 1     | 7         | AUTORIZADA |
        | 99      | 1     | 8         | AUTORIZADA |
        | 99      | 1     | 9         | NEGADA     |
        | 99      | 20    | 0         | NEGADA     |
        | 99      | 20    | 1         | AUTORIZADA |
        | 99      | 20    | 2         | AUTORIZADA |
        | 99      | 20    | 4         | AUTORIZADA |
        | 99      | 20    | 7         | AUTORIZADA |
        | 99      | 20    | 8         | AUTORIZADA |
        | 99      | 20    | 9         | NEGADA     |
        | 99      | 39    | 0         | NEGADA     |
        | 99      | 39    | 1         | AUTORIZADA |
        | 99      | 39    | 2         | AUTORIZADA |
        | 99      | 39    | 4         | AUTORIZADA |
        | 99      | 39    | 7         | AUTORIZADA |
        | 99      | 39    | 8         | AUTORIZADA |
        | 99      | 39    | 9         | NEGADA     |
        | 99      | 40    | 0         | NEGADA     |
        | 99      | 40    | 1         | AUTORIZADA |
        | 99      | 40    | 2         | AUTORIZADA |
        | 99      | 40    | 4         | AUTORIZADA |
        | 99      | 40    | 7         | AUTORIZADA |
        | 99      | 40    | 8         | AUTORIZADA |
        | 99      | 40    | 9         | NEGADA     |
        | 99      | 41    | 0         | NEGADA     |
        | 99      | 41    | 1         | NEGADA     |
        | 99      | 41    | 2         | NEGADA     |
        | 99      | 41    | 4         | NEGADA     |
        | 99      | 41    | 7         | NEGADA     |
        | 99      | 41    | 8         | NEGADA     |
        | 99      | 41    | 9         | NEGADA     |
        | 100     | -1    | 0         | NEGADA     |
        | 100     | -1    | 1         | NEGADA     |
        | 100     | -1    | 2         | NEGADA     |
        | 100     | -1    | 4         | NEGADA     |
        | 100     | -1    | 7         | NEGADA     |
        | 100     | -1    | 8         | NEGADA     |
        | 100     | -1    | 9         | NEGADA     |
        | 100     | 0     | 0         | NEGADA     |
        | 100     | 0     | 1         | AUTORIZADA |
        | 100     | 0     | 2         | AUTORIZADA |
        | 100     | 0     | 4         | AUTORIZADA |
        | 100     | 0     | 7         | AUTORIZADA |
        | 100     | 0     | 8         | AUTORIZADA |
        | 100     | 0     | 9         | NEGADA     |
        | 100     | 1     | 0         | NEGADA     |
        | 100     | 1     | 1         | AUTORIZADA |
        | 100     | 1     | 2         | AUTORIZADA |
        | 100     | 1     | 4         | AUTORIZADA |
        | 100     | 1     | 7         | AUTORIZADA |
        | 100     | 1     | 8         | AUTORIZADA |
        | 100     | 1     | 9         | NEGADA     |
        | 100     | 20    | 0         | NEGADA     |
        | 100     | 20    | 1         | AUTORIZADA |
        | 100     | 20    | 2         | AUTORIZADA |
        | 100     | 20    | 4         | AUTORIZADA |
        | 100     | 20    | 7         | AUTORIZADA |
        | 100     | 20    | 8         | AUTORIZADA |
        | 100     | 20    | 9         | NEGADA     |
        | 100     | 39    | 0         | NEGADA     |
        | 100     | 39    | 1         | AUTORIZADA |
        | 100     | 39    | 2         | AUTORIZADA |
        | 100     | 39    | 4         | AUTORIZADA |
        | 100     | 39    | 7         | AUTORIZADA |
        | 100     | 39    | 8         | AUTORIZADA |
        | 100     | 39    | 9         | NEGADA     |
        | 100     | 40    | 0         | NEGADA     |
        | 100     | 40    | 1         | AUTORIZADA |
        | 100     | 40    | 2         | AUTORIZADA |
        | 100     | 40    | 4         | AUTORIZADA |
        | 100     | 40    | 7         | AUTORIZADA |
        | 100     | 40    | 8         | AUTORIZADA |
        | 100     | 40    | 9         | NEGADA     |
        | 100     | 41    | 0         | NEGADA     |
        | 100     | 41    | 1         | NEGADA     |
        | 100     | 41    | 2         | NEGADA     |
        | 100     | 41    | 4         | NEGADA     |
        | 100     | 41    | 7         | NEGADA     |
        | 100     | 41    | 8         | NEGADA     |
        | 100     | 41    | 9         | NEGADA     |
        | 101     | -1    | 0         | NEGADA     |
        | 101     | -1    | 1         | NEGADA     |
        | 101     | -1    | 2         | NEGADA     |
        | 101     | -1    | 4         | NEGADA     |
        | 101     | -1    | 7         | NEGADA     |
        | 101     | -1    | 8         | NEGADA     |
        | 101     | -1    | 9         | NEGADA     |
        | 101     | 0     | 0         | NEGADA     |
        | 101     | 0     | 1         | NEGADA     |
        | 101     | 0     | 2         | NEGADA     |
        | 101     | 0     | 4         | NEGADA     |
        | 101     | 0     | 7         | NEGADA     |
        | 101     | 0     | 8         | NEGADA     |
        | 101     | 0     | 9         | NEGADA     |
        | 101     | 1     | 0         | NEGADA     |
        | 101     | 1     | 1         | NEGADA     |
        | 101     | 1     | 2         | NEGADA     |
        | 101     | 1     | 4         | NEGADA     |
        | 101     | 1     | 7         | NEGADA     |
        | 101     | 1     | 8         | NEGADA     |
        | 101     | 1     | 9         | NEGADA     |
        | 101     | 20    | 0         | NEGADA     |
        | 101     | 20    | 1         | NEGADA     |
        | 101     | 20    | 2         | NEGADA     |
        | 101     | 20    | 4         | NEGADA     |
        | 101     | 20    | 7         | NEGADA     |
        | 101     | 20    | 8         | NEGADA     |
        | 101     | 20    | 9         | NEGADA     |
        | 101     | 39    | 0         | NEGADA     |
        | 101     | 39    | 1         | NEGADA     |
        | 101     | 39    | 2         | NEGADA     |
        | 101     | 39    | 4         | NEGADA     |
        | 101     | 39    | 7         | NEGADA     |
        | 101     | 39    | 8         | NEGADA     |
        | 101     | 39    | 9         | NEGADA     |
        | 101     | 40    | 0         | NEGADA     |
        | 101     | 40    | 1         | NEGADA     |
        | 101     | 40    | 2         | NEGADA     |
        | 101     | 40    | 4         | NEGADA     |
        | 101     | 40    | 7         | NEGADA     |
        | 101     | 40    | 8         | NEGADA     |
        | 101     | 40    | 9         | NEGADA     |
        | 101     | 41    | 0         | NEGADA     |
        | 101     | 41    | 1         | NEGADA     |
        | 101     | 41    | 2         | NEGADA     |
        | 101     | 41    | 4         | NEGADA     |
        | 101     | 41    | 7         | NEGADA     |
        | 101     | 41    | 8         | NEGADA     |
        | 101     | 41    | 9         | NEGADA     |
