sonar.projectKey=seminario-sonarqube-jacoco
sonar.projectName=Seminario SonarQube JaCoCo
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

